#!/bin/sh
if !(ps -ax |grep -v grep| grep SSB_TRX.py) then
  sudo cp /home/pi/Langstone/splashload.bgra /dev/fb0
  taskset -c 1 python /home/pi/Langstone/SSB_TRX.py > /dev/null 2>&1 &
  sleep 10
  /home/pi/Langstone/GUI &
fi



