#!/bin/bash
cd /home/pi
cp /home/pi/Langstone/Langstone.conf /tmp
rm -rf /home/pi/Langstone
git clone -b Dev http://www.github.com/g4eml/Langstone
/home/pi/Langstone/build
cp /tmp/Langstone.conf /home/pi/Langstone



